version: '3.8'

services:
  tf-web-rcon:
    build: .
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"

